"""added price

Revision ID: 19357387c8d2
Revises: 706f74fa63d8
Create Date: 2023-09-16 15:02:02.366816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19357387c8d2'
down_revision = '706f74fa63d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
