"""add more columns

Revision ID: 706f74fa63d8
Revises: 74282b1040cd
Create Date: 2023-09-16 15:01:07.523101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706f74fa63d8'
down_revision = '74282b1040cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
